apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  text: "Hello World!"
  {{- with .Values.favorite }}
  drink: {{ .drink | default "None" | quote }}
  food: {{ .food | upper | quote }}
  {{- if eq .food "pizza" }}
  toppings: |-
    {{- range $.Values.pizzaToppings }}
    - {{ . | title | quote }}
    {{- end }}
  {{- end }}
  mug: {{ empty .drink | not | quote }}
  {{- end }}
