apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  text: {{ print (title .Chart.Name) "!" | cat "Hello" | quote }}
  {{- $toppings := .Values.pizzaToppings }}
  {{- with .Values.favorite }}
  {{- range $key, $val := . }}
  {{ $key }}: {{ $val | default "none" | quote }}
  {{- end }}
  {{- if eq .food "pizza" }}
  toppings: |-
    {{- range $toppings }}
    - {{ . | title | quote }}
    {{- end }}
  {{- end }}
  mug: {{ empty .drink | not | quote }}
  {{- end }}
