apiVersion: v1
kind: Service
metadata:
  name: {{ lower .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - port: {{ .Values.container.port }}
  selector:
    app: {{ .Chart.Name }}
  type: NodePort
